services:
    homestart:
        image: homestart
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        container_name: homestart
        environment:
            - HOST=
        ports:
            - "8080:8080"
            - "2345:2345"
        volumes:
            - ./:/app
            - /app/bin
